# Generated by Django 5.1.4 on 2025-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_features_icone_alter_service_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-start-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-start-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
    ]
