# Generated by Django 5.1.4 on 2025-01-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_features_icone_alter_service_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-start-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Feature1',
                'verbose_name_plural': 'Features1',
            },
        ),
        migrations.RenameModel(
            old_name='Features',
            new_name='Features1',
        ),
        migrations.AlterModelOptions(
            name='features1',
            options={'verbose_name': 'Feature2', 'verbose_name_plural': 'Features2'},
        ),
    ]
