# Generated by Django 5.1.4 on 2025-01-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_features2_rename_features_features1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features2',
        ),
        migrations.AlterModelOptions(
            name='features1',
            options={'verbose_name': 'Feature1', 'verbose_name_plural': 'Features1'},
        ),
    ]
